indexer_url      = "https://namada-mainnet-indexer.mellifera.network"
rpc_url          = "https://namada-mainnet-rpc.mellifera.network"
masp_indexer_url = "https://namada-mainnet-masp.mellifera.network"
